# Tensor Manipulation
![](https://drive.google.com/uc?id=1gs6YJoiFLfA_lMZp-Tbty0D20C4wsp2S)

## tensor manipulation

- reshaping
- slicing
- joining or splitting
- transposing and permuting dimension

In [1]:
import torch

In [5]:
# reshaping tensors
# reshape
# view

original_tensor = torch.arange(12)
print(original_tensor)
print(original_tensor.nelement())
print(original_tensor.ndim)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
12
1


In [7]:
# 2x6--> 12

reshaped_tensor = original_tensor.reshape(2,6)
print(reshaped_tensor)
print(reshaped_tensor.ndim)
print(reshaped_tensor.nelement())

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
2
12


In [8]:
reshaped_tensor = original_tensor.reshape(3,4)
print(reshaped_tensor)
print(reshaped_tensor.ndim)
print(reshaped_tensor.nelement())

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
2
12


In [10]:
# view
print(original_tensor.is_contiguous())
flattened_tensor = original_tensor.view(-1)
print(flattened_tensor)

True
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


## Slicing
Extract specific portions of tensors

In [11]:
tensor_a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(tensor_a)
print(tensor_a.ndim)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2


In [12]:
print(tensor_a[0])

tensor([1, 2, 3])


In [15]:
tensor_a[:,2]

tensor([3, 6, 9])

In [16]:
print(tensor_a.shape)

torch.Size([3, 3])


In [18]:
sub_tensor = tensor_a[1:,1:]
print(sub_tensor.shape)
print(sub_tensor)

torch.Size([2, 2])
tensor([[5, 6],
        [8, 9]])


## Joining tensors

In [21]:
# torch.cat() --> merges tensors along an exisiting dimesion.
tensor1 = torch.tensor([[1,2],[3,4]])
tensor2 = torch.tensor([[5,6],[7,8]])

print(tensor1)
print(tensor2)

print("="*20)

concat_tensor_rows = torch.cat((tensor1, tensor2), dim=0)
concat_tensor_colm = torch.cat((tensor1, tensor2), dim=1)

print(concat_tensor_rows)
print(concat_tensor_colm)

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [24]:
# stack --> created a new dimension, increases the tensor's rank

print(tensor1.shape)
print(tensor2.shape)

print("="*20)
stack_tensor_rows = torch.stack((tensor1, tensor2), dim=0)
stack_tensor_colm = torch.stack((tensor1, tensor2), dim=1)

print(stack_tensor_rows.shape)
print(stack_tensor_colm.shape)

print(stack_tensor_rows)
print(stack_tensor_colm)


torch.Size([2, 2])
torch.Size([2, 2])
torch.Size([2, 2, 2])
torch.Size([2, 2, 2])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


## Splitting tensors
- torch.chunk() --> divides your tensor into equal-sized chunks
- torch.split() --> allows eneven splitting based on size

In [42]:
# torch.chunk

origin_tensor = torch.arange(12)

chunks = torch.chunk(origin_tensor, 5, dim=0)

print(chunks)

for chunk in chunks:
  print(chunk)

(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8]), tensor([ 9, 10, 11]))
tensor([0, 1, 2])
tensor([3, 4, 5])
tensor([6, 7, 8])
tensor([ 9, 10, 11])


In [44]:
# torch.split

splits = torch.split(origin_tensor, 7, dim=0)

print(splits)

for split in splits:
  print(split)

(tensor([0, 1, 2, 3, 4, 5, 6]), tensor([ 7,  8,  9, 10, 11]))
tensor([0, 1, 2, 3, 4, 5, 6])
tensor([ 7,  8,  9, 10, 11])


# Transposing and premuting

- transpose() -->swaps two dimesnion. mxn --> nxm
- premute() --> rearranges all dimension in the specified order

In [46]:
# transpose

tensor_original = torch.arange(24).reshape(12,2)

transposed_tensor = tensor_original.transpose(0,1)

print(tensor_original)

print(tensor_original.shape)
print(transposed_tensor.shape)

print(transposed_tensor)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]])
torch.Size([12, 2])
torch.Size([2, 12])
tensor([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23]])


In [52]:
tensor_original = torch.arange(24).reshape(2,3,4)

print(2*3*4)

print(tensor_original.shape)
print(tensor_original)

# [0,1,2]
permuted_tensor = tensor_original.permute(2, 0, 1)
print(permuted_tensor)
print(permuted_tensor.shape)

24
torch.Size([2, 3, 4])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[ 0,  4,  8],
         [12, 16, 20]],

        [[ 1,  5,  9],
         [13, 17, 21]],

        [[ 2,  6, 10],
         [14, 18, 22]],

        [[ 3,  7, 11],
         [15, 19, 23]]])
torch.Size([4, 2, 3])


In [ ]:
l = [4,0,1,2,3,0]

# Cloning and detaching

In [55]:
import copy

a = [1,2,3]
b = copy.deepcopy(a)

print(a)
print(b)

[1, 2, 3]
[1, 2, 3]


In [56]:
tensor = torch.ones(3,3, requires_grad=True) # part of computation graph

cloned_tensor = tensor.clone() # # part of computation graph

detached_tensor = tensor.detach() # this code will detach the tensor from the computation graph
# # non a part of computation graph
# but storage will be same as the original ones